### ISSUE TITLE
Expand ~ to $HOME in config file

### ISSUE THREAD

**Issue by murlakatamenka** [adamperkowski/nvrs#39]
`nvrs` doesn't expand `~` to user home directory `$HOME`, [unlike `nvchecker`](https://github.com/lilydjwg/nvchecker/blob/4d5e29f26b536dc261fba77ab12585c49642f91a/nvchecker/core.py#L204-L208)

```toml
[__config__]
oldver = "~/.config/nvrs/old.json"
newver = "~/.config/nvrs/new.json"
```

Also the error messase isn't helpful at all:

```sh
# RUST_LOG=1 or RUST_BACKTRACE=1 won't help
$ nvrs

! io error: No such file or directory (os error 2)
```
